version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php_fpm_app
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
